ROX-12977: Update to align with current Red Hat Insights starter app
RedHatInsights/acs-ui pull request #72
Opened 2023-03-28 06:22 UTC by bradr5

## Description
Update everything to align with current Red Hat Insights starter app

This satisfies the following tasks:

- ROX-12958
- ROX-14786
- ROX-12977

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:**

2023-03-28 17:47 UTC, ryelo commented on .travis.yml
> +      - secure: juuizlfiQolXbqy4L2nfODB1K8xiSGvUrzsT3XeXIsQqX7yCYVvnRUssKLbqgLM9m85kgXJk1ef0qwjJoliNqGcrALTZLHPTkxWwTnV7tPEVS/4uQPSyy+DDHDwrTzCrF3qhCqyKJ6vB18z22qm3qLgStmNj4p1ZLznsdJR/u7U3spJ+WLL70QS
This can be removed. It's getting deprecated next week.

2023-03-28 17:47 UTC, sachaudh reviewed
Oh nice, we get Typescript with these changes. Let me do a more thorough check since there are a lot of changes going into this PR

2023-03-28 23:03 UTC, vjwilson requested changes
I'm fine with this overall, but we need to update the README, too, to reflect the new dev process.

(plus, a couple of nits)

2023-03-28 23:03 UTC, vjwilson commented on src/routes/NoPermissionsPage/NoPermissionsPage.tsx
> +const NoPermissionsPage = () => {
nit: Some of components are still defined with `function` keyword, but this and `OopsPage.tsx` use arrow function definition.

While rare, there are some weird edge cases that can occur with top-level arrow functions, so I'd prefer we leave them with the `function` keyword.

2023-03-28 23:03 UTC, vjwilson commented on src/routes/OopsPage/OopsPage.tsx
> +const OopsPage = () => {
nit: Prefer `function` keyword for top-level functions

2023-04-04 10:42 UTC, vjwilson approved these changes

2023-04-05 23:26 UTC, merged